[package]
name = "rusty_snake_game"
version = "0.1.0"
authors = ["Piotr Gródek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston = "0.49.0"
rand = "0.7.2"
piston_window = "0.105.0"
